apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gef8w1s9y-java-quarkus
  janus-idp.io/tekton: gef8w1s9y-java-quarkus
  backstage.io/kubernetes-id: gef8w1s9y-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gef8w1s9y-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
